# Generated by Django 5.2.5 on 2025-08-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
